services:
  - type: web
    name: skulz-school-crm
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --no-input && python manage.py setup_schools"
    startCommand: "gunicorn skubackend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: "*.onrender.com"
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_EMAIL
        value: admin@skulz.local
    databases:
      - name: skulz_db
        engine: postgresql
        plan: free
